param(
	[string]$SourceRoot = (Join-Path $PSScriptRoot '..\assets\ui-icons'),
	[string]$OutputPath = (Join-Path $PSScriptRoot '..\src\shared\UiIcons.luau')
)

Add-Type -AssemblyName System.Drawing

$icons = [ordered]@{
	upgrade = 'upgrade.png'
	chests = 'chests.png'
	rebirth = 'rebirth.png'
	teleport = 'teleport.png'
	dailyReward = 'daily-reward.png'
}

function Get-RleBase64([string]$Path) {
	$bitmap = [System.Drawing.Bitmap]::FromFile($Path)
	try {
		if ($bitmap.Width -ne 64 -or $bitmap.Height -ne 64) {
			throw "Expected a 64x64 icon: $Path"
		}

		$bytes = [System.Collections.Generic.List[byte]]::new()
		$last = $null
		$run = 0

		for ($y = 0; $y -lt $bitmap.Height; $y++) {
			for ($x = 0; $x -lt $bitmap.Width; $x++) {
				$color = $bitmap.GetPixel($x, $y)
				$current = @($color.R, $color.G, $color.B, $color.A)
				$same = $last -ne $null -and $current[0] -eq $last[0] -and $current[1] -eq $last[1] -and $current[2] -eq $last[2] -and $current[3] -eq $last[3]

				if ($same -and $run -lt 255) {
					$run++
					continue
				}

				if ($run -gt 0) {
					$bytes.Add([byte]$run)
					foreach ($channel in $last) { $bytes.Add([byte]$channel) }
				}

				$last = $current
				$run = 1
			}
		}

		if ($run -gt 0) {
			$bytes.Add([byte]$run)
			foreach ($channel in $last) { $bytes.Add([byte]$channel) }
		}

		return [Convert]::ToBase64String($bytes.ToArray())
	} finally {
		$bitmap.Dispose()
	}
}

$entries = foreach ($name in $icons.Keys) {
	$encoded = Get-RleBase64 (Join-Path $SourceRoot $icons[$name])
	"`t${name} = `"${encoded}`","
}

$template = @'
-- Generated by tools/generate-ui-icons.ps1 from the selected Free Icon Pack files.
-- Pixels are stored as compact run-length encoded RGBA so no Roblox asset upload is required.
local AssetService = game:GetService("AssetService")
local TweenService = game:GetService("TweenService")

local UiIcons = {}

local ICON_SIZE = Vector2.new(64, 64)
local PIXEL_COUNT = 64 * 64

local encodedIcons = {
__ICON_ENTRIES__
}

local cachedContent = {}
local warnedIcons = {}

local function decodeBase64(value)
	local alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	local lookup = {}
	for index = 1, #alphabet do
		lookup[string.byte(alphabet, index)] = index - 1
	end

	local output = table.create(math.ceil(#value * 0.75))
	local outputIndex = 1
	for index = 1, #value, 4 do
		local a = lookup[string.byte(value, index)] or 0
		local b = lookup[string.byte(value, index + 1)] or 0
		local cByte = string.byte(value, index + 2)
		local dByte = string.byte(value, index + 3)
		local c = lookup[cByte] or 0
		local d = lookup[dByte] or 0
		local combined = a * 262144 + b * 4096 + c * 64 + d

		output[outputIndex] = string.char(math.floor(combined / 65536) % 256)
		outputIndex += 1
		if cByte ~= string.byte("=") then
			output[outputIndex] = string.char(math.floor(combined / 256) % 256)
			outputIndex += 1
		end
		if dByte ~= string.byte("=") then
			output[outputIndex] = string.char(combined % 256)
			outputIndex += 1
		end
	end

	return table.concat(output)
end

local function createContent(name)
	local encoded = encodedIcons[name]
	if not encoded then
		return nil
	end

	local editableImage = AssetService:CreateEditableImage({ Size = ICON_SIZE })
	if not editableImage then
		return nil
	end

	local packed = decodeBase64(encoded)
	local pixels = buffer.create(PIXEL_COUNT * 4)
	local sourceOffset = 1
	local targetOffset = 0

	while sourceOffset <= #packed do
		local run = string.byte(packed, sourceOffset)
		local red = string.byte(packed, sourceOffset + 1)
		local green = string.byte(packed, sourceOffset + 2)
		local blue = string.byte(packed, sourceOffset + 3)
		local alpha = string.byte(packed, sourceOffset + 4)
		sourceOffset += 5

		for _ = 1, run do
			buffer.writeu8(pixels, targetOffset, red)
			buffer.writeu8(pixels, targetOffset + 1, green)
			buffer.writeu8(pixels, targetOffset + 2, blue)
			buffer.writeu8(pixels, targetOffset + 3, alpha)
			targetOffset += 4
		end
	end

	assert(targetOffset == PIXEL_COUNT * 4, `Invalid pixel data for icon {name}`)
	editableImage:WritePixelsBuffer(Vector2.zero, ICON_SIZE, pixels)

	return {
		content = Content.fromObject(editableImage),
		image = editableImage,
	}
end

function UiIcons.apply(imageLabel, name)
	local cached = cachedContent[name]
	if not cached then
		local success, result = pcall(createContent, name)
		if not success or not result then
			if not warnedIcons[name] then
				warnedIcons[name] = true
				warn(`Unable to create embedded UI icon {name}: {result}`)
			end
			return false
		end
		cached = result
		cachedContent[name] = cached
	end

	local success, message = pcall(function()
		imageLabel.ImageContent = cached.content
	end)
	if not success and not warnedIcons[name] then
		warnedIcons[name] = true
		warn(`Unable to apply embedded UI icon {name}: {message}`)
	end

	return success
end

function UiIcons.create(parent, name, size, position, zIndex)
	local image = Instance.new("ImageLabel")
	image.Name = "Icon"
	image.Size = size
	image.Position = position
	image.BackgroundTransparency = 1
	image.BorderSizePixel = 0
	image.ScaleType = Enum.ScaleType.Fit
	image.ZIndex = zIndex or parent.ZIndex + 1
	image.Parent = parent
	UiIcons.apply(image, name)
	return image
end

function UiIcons.decorateMenuButton(button, label, name)
	button.Size = UDim2.new(1, -6, 1, -6)
	button.Position = UDim2.fromOffset(3, 3)
	button.BackgroundTransparency = 1

	local buttonContainer = button.Parent
	if buttonContainer and buttonContainer:IsA("GuiObject") then
		buttonContainer.BackgroundTransparency = 0.4
	end

	label.Size = UDim2.new(1, 14, 0, 24)
	label.Position = UDim2.new(0, -7, 1, -12)
	label.FontFace = Font.new(
		"rbxasset://fonts/families/Montserrat.json",
		Enum.FontWeight.ExtraBold,
		Enum.FontStyle.Normal
	)
	label.BackgroundTransparency = 1
	label.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
	label.TextStrokeTransparency = 1
	label.TextScaled = false
	label.TextSize = 14
	label.TextXAlignment = Enum.TextXAlignment.Center
	label.TextYAlignment = Enum.TextYAlignment.Center
	label.ZIndex = button.ZIndex + 3

	for _, child in ipairs(label:GetChildren()) do
		if child:IsA("UIStroke") then
			child.ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual
			child.Color = Color3.fromRGB(0, 0, 0)
			child.Thickness = 1.5
			child.Transparency = 0
		end
	end

	local textGradient = Instance.new("UIGradient")
	textGradient.Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
		ColorSequenceKeypoint.new(0.5, Color3.fromRGB(255, 255, 255)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(145, 145, 155)),
	})
	textGradient.Rotation = 90
	textGradient.Parent = label

	local shineOverlay = Instance.new("Frame")
	shineOverlay.Name = "ShineOverlay"
	shineOverlay.Size = UDim2.fromScale(1, 1)
	shineOverlay.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	shineOverlay.BorderSizePixel = 0
	shineOverlay.ZIndex = button.ZIndex + 2
	shineOverlay.Parent = button

	local shineGradient = Instance.new("UIGradient")
	shineGradient.Rotation = 18
	shineGradient.Offset = Vector2.new(-1.2, 0)
	shineGradient.Transparency = NumberSequence.new({
		NumberSequenceKeypoint.new(0, 1),
		NumberSequenceKeypoint.new(0.42, 1),
		NumberSequenceKeypoint.new(0.48, 0.88),
		NumberSequenceKeypoint.new(0.5, 0.55),
		NumberSequenceKeypoint.new(0.52, 0.88),
		NumberSequenceKeypoint.new(0.58, 1),
		NumberSequenceKeypoint.new(1, 1),
	})
	shineGradient.Parent = shineOverlay

	TweenService:Create(
		shineGradient,
		TweenInfo.new(1.1, Enum.EasingStyle.Linear, Enum.EasingDirection.Out, -1, false, 2.2),
		{ Offset = Vector2.new(1.2, 0) }
	):Play()

	local innerBorder = Instance.new("Frame")
	innerBorder.Name = "InnerBorder"
	innerBorder.Size = UDim2.fromScale(1, 1)
	innerBorder.Position = UDim2.fromScale(0, 0)
	innerBorder.BackgroundTransparency = 1
	innerBorder.BorderSizePixel = 0
	innerBorder.ZIndex = button.ZIndex + 1
	innerBorder.Parent = button

	local innerStroke = Instance.new("UIStroke")
	innerStroke.Color = Color3.fromRGB(255, 255, 255)
	innerStroke.Thickness = 2
	innerStroke.Transparency = 0
	innerStroke.Parent = innerBorder

	local innerStrokeGradient = Instance.new("UIGradient")
	innerStrokeGradient.Rotation = 90
	innerStrokeGradient.Transparency = NumberSequence.new({
		NumberSequenceKeypoint.new(0, 0.82),
		NumberSequenceKeypoint.new(1, 0.45),
	})
	innerStrokeGradient.Parent = innerStroke

	local icon = UiIcons.create(
		button,
		name,
		UDim2.fromOffset(58, 58),
		UDim2.new(0.5, 0, 0, 1),
		button.ZIndex + 1
	)
	icon.AnchorPoint = Vector2.new(0.5, 0)
	return icon
end

return UiIcons
'@

$content = $template.Replace('__ICON_ENTRIES__', ($entries -join "`r`n"))
$resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)
[System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($resolvedOutput)) | Out-Null
[System.IO.File]::WriteAllText($resolvedOutput, $content, [System.Text.UTF8Encoding]::new($false))
